// 词根数据 Part 2: graph/gram ~ scrib/script
const wordRootsPart2 = [
  {
    root: "graph/gram",
    meaning: "写，画",
    category: "交流",
    words: [
      { word: "graph", meaning: "图表；曲线图", level: "CET-4" },
      { word: "graphic", meaning: "图形的；图表的", level: "CET-4" },
      { word: "photograph", meaning: "照片；拍照", level: "CET-4" },
      { word: "photography", meaning: "摄影；摄影术", level: "CET-4" },
      { word: "paragraph", meaning: "段落", level: "CET-4" },
      { word: "geography", meaning: "地理；地理学", level: "CET-4" },
      { word: "biography", meaning: "传记", level: "CET-4" },
      { word: "autobiography", meaning: "自传", level: "CET-6" },
      { word: "grammar", meaning: "语法；文法", level: "CET-4" },
      { word: "gram", meaning: "克", level: "CET-4" },
      { word: "diagram", meaning: "图表；图解", level: "CET-4" },
      { word: "program", meaning: "程序；节目；计划", level: "CET-4" },
      { word: "telegram", meaning: "电报", level: "CET-4" },
      { word: "telegraph", meaning: "电报机；打电报", level: "CET-6" },
      { word: "calligraphy", meaning: "书法", level: "CET-6" },
    ],
  },
  {
    root: "ject",
    meaning: "投，掷",
    category: "动作",
    words: [
      { word: "project", meaning: "项目；投射", level: "CET-4" },
      { word: "projector", meaning: "投影仪", level: "CET-4" },
      { word: "reject", meaning: "拒绝；排斥", level: "CET-4" },
      { word: "rejection", meaning: "拒绝；驳回", level: "CET-6" },
      { word: "inject", meaning: "注射；注入", level: "CET-4" },
      { word: "injection", meaning: "注射；注入", level: "CET-4" },
      { word: "eject", meaning: "弹出；驱逐", level: "CET-6" },
      { word: "subject", meaning: "主题；学科；受...影响的", level: "CET-4" },
      { word: "subjective", meaning: "主观的", level: "CET-6" },
      { word: "objective", meaning: "客观的；目标", level: "CET-4" },
      { word: "object", meaning: "物体；目标；反对", level: "CET-4" },
      { word: "objection", meaning: "反对；异议", level: "CET-4" },
      { word: "trajectory", meaning: "轨迹；弹道", level: "CET-6" },
    ],
  },
  {
    root: "jud/jur",
    meaning: "判断，法律",
    category: "社会",
    words: [
      { word: "judge", meaning: "判断；法官；裁判", level: "CET-4" },
      { word: "judgment", meaning: "判断；判决", level: "CET-4" },
      { word: "judicial", meaning: "司法的；法庭的", level: "CET-6" },
      { word: "prejudice", meaning: "偏见；歧视", level: "CET-4" },
      { word: "jury", meaning: "陪审团", level: "CET-4" },
      { word: "jurisdiction", meaning: "管辖权；司法权", level: "CET-6" },
      { word: "injury", meaning: "伤害；损害", level: "CET-4" },
      { word: "injure", meaning: "伤害；损害", level: "CET-4" },
      { word: "adjust", meaning: "调整；适应", level: "CET-4" },
      { word: "just", meaning: "公正的；正好", level: "CET-4" },
      { word: "justice", meaning: "正义；公正", level: "CET-4" },
      { word: "justify", meaning: "证明正当", level: "CET-4" },
      { word: "unjust", meaning: "不公正的", level: "CET-6" },
    ],
  },
  {
    root: "lect/leg",
    meaning: "选择，收集",
    category: "动作",
    words: [
      { word: "collect", meaning: "收集；集合", level: "CET-4" },
      { word: "collection", meaning: "收藏；收集品", level: "CET-4" },
      { word: "collective", meaning: "集体的；共同的", level: "CET-4" },
      { word: "elect", meaning: "选举；选择", level: "CET-4" },
      { word: "election", meaning: "选举；推举", level: "CET-4" },
      { word: "select", meaning: "选择；挑选", level: "CET-4" },
      { word: "selection", meaning: "选择；挑选", level: "CET-4" },
      { word: "lecture", meaning: "讲座；演讲", level: "CET-4" },
      { word: "intellect", meaning: "智力；才智", level: "CET-6" },
      { word: "intellectual", meaning: "智力的；知识分子", level: "CET-4" },
      { word: "intelligent", meaning: "聪明的；智慧的", level: "CET-4" },
      { word: "intelligence", meaning: "智力；情报", level: "CET-4" },
      { word: "neglect", meaning: "忽视；忽略", level: "CET-4" },
      { word: "elegant", meaning: "优雅的；精美的", level: "CET-4" },
      { word: "legend", meaning: "传说；传奇", level: "CET-4" },
      { word: "delegate", meaning: "代表；委派", level: "CET-4" },
      { word: "diligent", meaning: "勤奋的；勤勉的", level: "CET-6" },
    ],
  },
  {
    root: "liber",
    meaning: "自由",
    category: "社会",
    words: [
      { word: "liberal", meaning: "自由的；开明的", level: "CET-4" },
      { word: "liberty", meaning: "自由；解放", level: "CET-4" },
      { word: "liberate", meaning: "解放；释放", level: "CET-4" },
      { word: "liberation", meaning: "解放", level: "CET-4" },
      { word: "liberalism", meaning: "自由主义", level: "CET-6" },
      { word: "illiberal", meaning: "狭隘的；保守的", level: "CET-6" },
    ],
  },
  {
    root: "log",
    meaning: "语言，思想",
    category: "思维",
    words: [
      { word: "logic", meaning: "逻辑；逻辑学", level: "CET-4" },
      { word: "logical", meaning: "逻辑的；合理的", level: "CET-4" },
      { word: "dialog/dialogue", meaning: "对话", level: "CET-4" },
      { word: "apologize", meaning: "道歉；认错", level: "CET-4" },
      { word: "apology", meaning: "道歉；认错", level: "CET-4" },
      { word: "catalog/catalogue", meaning: "目录", level: "CET-4" },
      { word: "analogy", meaning: "类比；类推", level: "CET-6" },
      { word: "slogan", meaning: "口号；标语", level: "CET-4" },
      { word: "monologue", meaning: "独白", level: "CET-6" },
      { word: "prologue", meaning: "开场白；序幕", level: "CET-6" },
      { word: "epilogue", meaning: "结语；尾声", level: "CET-6" },
    ],
  },
  {
    root: "luc/lum",
    meaning: "光",
    category: "自然",
    words: [
      { word: "lucid", meaning: "清晰的；透明的", level: "CET-6" },
      { word: "illuminate", meaning: "照亮；阐明", level: "CET-6" },
      { word: "illumination", meaning: "照明；启发", level: "CET-6" },
      { word: "luminous", meaning: "发光的；明亮的", level: "CET-6" },
      { word: "luminary", meaning: "杰出人物；发光体", level: "CET-6" },
      { word: "luster", meaning: "光泽；光彩", level: "CET-6" },
      { word: "illustrate", meaning: "说明；阐明", level: "CET-4" },
      { word: "illustration", meaning: "说明；插图", level: "CET-4" },
    ],
  },
  {
    root: "magn",
    meaning: "大",
    category: "性质",
    words: [
      { word: "magnificent", meaning: "壮丽的；宏伟的", level: "CET-4" },
      { word: "magnify", meaning: "放大；扩大", level: "CET-6" },
      { word: "magnitude", meaning: "大小；规模；重要性", level: "CET-6" },
      { word: "magnate", meaning: "巨头；大亨", level: "CET-6" },
      { word: "magnet", meaning: "磁铁；有吸引力的人", level: "CET-4" },
      { word: "magnetic", meaning: "磁性的；有吸引力的", level: "CET-4" },
      { word: "magnesium", meaning: "镁", level: "CET-6" },
    ],
  },
  {
    root: "man/manu",
    meaning: "手",
    category: "身体",
    words: [
      { word: "manual", meaning: "手册；手工的", level: "CET-4" },
      { word: "manage", meaning: "管理；经营", level: "CET-4" },
      { word: "management", meaning: "管理；经营", level: "CET-4" },
      { word: "manager", meaning: "经理；管理者", level: "CET-4" },
      { word: "manuscript", meaning: "手稿；原稿", level: "CET-6" },
      { word: "manufacture", meaning: "制造；生产", level: "CET-4" },
      { word: "manufacturer", meaning: "制造商；厂商", level: "CET-4" },
      { word: "manipulate", meaning: "操纵；操作", level: "CET-6" },
      { word: "manifest", meaning: "显示；表明；明显的", level: "CET-6" },
      { word: "maneuver", meaning: "机动；操纵", level: "CET-6" },
      { word: "emancipate", meaning: "解放；释放", level: "CET-6" },
    ],
  },
  {
    root: "mand",
    meaning: "命令",
    category: "社会",
    words: [
      { word: "command", meaning: "命令；指挥；掌握", level: "CET-4" },
      { word: "commander", meaning: "指挥官；司令", level: "CET-4" },
      { word: "demand", meaning: "要求；需求", level: "CET-4" },
      { word: "mandate", meaning: "授权；命令", level: "CET-6" },
      { word: "mandatory", meaning: "强制性的；义务的", level: "CET-6" },
      { word: "commend", meaning: "推荐；称赞", level: "CET-6" },
    ],
  },
  {
    root: "mem",
    meaning: "记忆",
    category: "思维",
    words: [
      { word: "memory", meaning: "记忆；回忆", level: "CET-4" },
      { word: "memorize", meaning: "记住；背诵", level: "CET-4" },
      { word: "memorial", meaning: "纪念的；纪念碑", level: "CET-4" },
      { word: "memoir", meaning: "回忆录；传记", level: "CET-6" },
      { word: "commemorate", meaning: "纪念；庆祝", level: "CET-6" },
      { word: "remember", meaning: "记住；回想起", level: "CET-4" },
      { word: "remind", meaning: "提醒；使想起", level: "CET-4" },
      { word: "memento", meaning: "纪念品", level: "CET-6" },
    ],
  },
  {
    root: "ment",
    meaning: "心，思",
    category: "思维",
    words: [
      { word: "mental", meaning: "精神的；智力的", level: "CET-4" },
      { word: "mention", meaning: "提到；说起", level: "CET-4" },
      { word: "comment", meaning: "评论；注释", level: "CET-4" },
      { word: "commentary", meaning: "评论；解说", level: "CET-6" },
      { word: "commentator", meaning: "评论员；解说员", level: "CET-6" },
    ],
  },
  {
    root: "min",
    meaning: "小",
    category: "性质",
    words: [
      { word: "minute", meaning: "分钟；微小的", level: "CET-4" },
      { word: "minimum", meaning: "最小值；最低的", level: "CET-4" },
      { word: "minor", meaning: "较小的；次要的", level: "CET-4" },
      { word: "minority", meaning: "少数；少数民族", level: "CET-4" },
      { word: "minus", meaning: "减去；负的", level: "CET-4" },
      { word: "minimize", meaning: "最小化；减少", level: "CET-6" },
      { word: "miniature", meaning: "微型的；缩影", level: "CET-6" },
      { word: "minister", meaning: "部长；大臣", level: "CET-4" },
      { word: "ministry", meaning: "部；政府部门", level: "CET-4" },
      { word: "administer", meaning: "管理；执行", level: "CET-6" },
      { word: "administration", meaning: "管理；行政", level: "CET-4" },
      { word: "diminish", meaning: "减少；缩小", level: "CET-6" },
    ],
  },
  {
    root: "miss/mit",
    meaning: "送，发",
    category: "动作",
    words: [
      { word: "miss", meaning: "想念；错过", level: "CET-4" },
      { word: "mission", meaning: "使命；任务", level: "CET-4" },
      { word: "missionary", meaning: "传教士", level: "CET-6" },
      { word: "missile", meaning: "导弹；投射物", level: "CET-4" },
      { word: "message", meaning: "消息；信息", level: "CET-4" },
      { word: "admit", meaning: "承认；准许进入", level: "CET-4" },
      { word: "admission", meaning: "承认；录取", level: "CET-4" },
      { word: "commit", meaning: "犯；承诺；委托", level: "CET-4" },
      { word: "commitment", meaning: "承诺；投入", level: "CET-4" },
      { word: "committee", meaning: "委员会", level: "CET-4" },
      { word: "dismiss", meaning: "解雇；解散", level: "CET-4" },
      { word: "emit", meaning: "发出；发射", level: "CET-4" },
      { word: "emission", meaning: "排放；发射", level: "CET-4" },
      { word: "omit", meaning: "省略；遗漏", level: "CET-4" },
      { word: "permit", meaning: "许可；允许", level: "CET-4" },
      { word: "permission", meaning: "许可；批准", level: "CET-4" },
      { word: "submit", meaning: "提交；服从", level: "CET-4" },
      { word: "transmit", meaning: "传输；传播", level: "CET-4" },
      { word: "transmission", meaning: "传输；传播", level: "CET-4" },
      { word: "intermittent", meaning: "间歇的；断断续续的", level: "CET-6" },
    ],
  },
  {
    root: "mob/mot/mov",
    meaning: "移动",
    category: "动作",
    words: [
      { word: "mobile", meaning: "可移动的；活跃的", level: "CET-4" },
      { word: "mobility", meaning: "流动性；移动性", level: "CET-6" },
      { word: "automobile", meaning: "汽车", level: "CET-4" },
      { word: "motion", meaning: "运动；动作", level: "CET-4" },
      { word: "motive", meaning: "动机；目的", level: "CET-4" },
      { word: "motivate", meaning: "激励；激发", level: "CET-4" },
      { word: "motivation", meaning: "动机；动力", level: "CET-4" },
      { word: "motor", meaning: "马达；发动机", level: "CET-4" },
      { word: "promote", meaning: "促进；提升", level: "CET-4" },
      { word: "promotion", meaning: "晋升；促销", level: "CET-4" },
      { word: "emotion", meaning: "情感；情绪", level: "CET-4" },
      { word: "emotional", meaning: "情感的；情绪的", level: "CET-4" },
      { word: "move", meaning: "移动；搬家", level: "CET-4" },
      { word: "movement", meaning: "运动；移动", level: "CET-4" },
      { word: "remove", meaning: "移除；消除", level: "CET-4" },
      { word: "remote", meaning: "遥远的；偏僻的", level: "CET-4" },
      { word: "commute", meaning: "通勤；交换", level: "CET-4" },
    ],
  },
  {
    root: "nat",
    meaning: "出生，自然",
    category: "生命",
    words: [
      { word: "nature", meaning: "自然；性质", level: "CET-4" },
      { word: "natural", meaning: "自然的；天然的", level: "CET-4" },
      { word: "naturally", meaning: "自然地；天生地", level: "CET-4" },
      { word: "nation", meaning: "国家；民族", level: "CET-4" },
      { word: "national", meaning: "国家的；民族的", level: "CET-4" },
      { word: "native", meaning: "本地的；土生的", level: "CET-4" },
      { word: "innate", meaning: "天生的；固有的", level: "CET-6" },
      { word: "renaissance", meaning: "文艺复兴；复兴", level: "CET-6" },
      { word: "naive", meaning: "天真的；幼稚的", level: "CET-4" },
    ],
  },
  {
    root: "nov",
    meaning: "新",
    category: "性质",
    words: [
      { word: "novel", meaning: "小说；新颖的", level: "CET-4" },
      { word: "novelty", meaning: "新颖；新奇事物", level: "CET-6" },
      { word: "novice", meaning: "新手；初学者", level: "CET-6" },
      { word: "innovate", meaning: "创新；革新", level: "CET-4" },
      { word: "innovation", meaning: "创新；革新", level: "CET-4" },
      { word: "innovative", meaning: "创新的；革新的", level: "CET-4" },
      { word: "renovate", meaning: "翻新；修复", level: "CET-6" },
    ],
  },
  {
    root: "ord",
    meaning: "顺序",
    category: "性质",
    words: [
      { word: "order", meaning: "顺序；命令；订购", level: "CET-4" },
      { word: "orderly", meaning: "有序的；整齐的", level: "CET-4" },
      { word: "ordinary", meaning: "普通的；平常的", level: "CET-4" },
      { word: "extraordinary", meaning: "非凡的；特别的", level: "CET-4" },
      { word: "coordinate", meaning: "协调；坐标", level: "CET-4" },
      { word: "coordination", meaning: "协调；协作", level: "CET-4" },
      { word: "subordinate", meaning: "从属的；下属", level: "CET-6" },
      { word: "insubordinate", meaning: "不服从的；反抗的", level: "CET-6" },
    ],
  },
  {
    root: "pel/puls",
    meaning: "推，驱",
    category: "动作",
    words: [
      { word: "compel", meaning: "强迫；迫使", level: "CET-4" },
      { word: "compulsion", meaning: "强制；冲动", level: "CET-6" },
      { word: "compulsory", meaning: "强制的；义务的", level: "CET-4" },
      { word: "expel", meaning: "驱逐；开除", level: "CET-6" },
      { word: "impulse", meaning: "冲动；推动", level: "CET-6" },
      { word: "impulsive", meaning: "冲动的；易冲动的", level: "CET-6" },
      { word: "propel", meaning: "推动；推进", level: "CET-6" },
      { word: "propeller", meaning: "螺旋桨；推进器", level: "CET-6" },
      { word: "repel", meaning: "击退；排斥", level: "CET-6" },
      { word: "pulse", meaning: "脉搏；脉冲", level: "CET-4" },
    ],
  },
  {
    root: "pend",
    meaning: "悬挂",
    category: "动作",
    words: [
      { word: "depend", meaning: "依赖；取决于", level: "CET-4" },
      { word: "dependent", meaning: "依赖的；从属的", level: "CET-4" },
      { word: "independence", meaning: "独立；自主", level: "CET-4" },
      { word: "independent", meaning: "独立的；自主的", level: "CET-4" },
      { word: "suspend", meaning: "暂停；悬挂", level: "CET-4" },
      { word: "suspense", meaning: "悬念；焦虑", level: "CET-6" },
      { word: "pending", meaning: "待定的；即将发生的", level: "CET-6" },
      { word: "pendulum", meaning: "钟摆；摇摆不定", level: "CET-6" },
      { word: "appendix", meaning: "附录；阑尾", level: "CET-4" },
      { word: "expense", meaning: "费用；开支", level: "CET-4" },
      { word: "expensive", meaning: "昂贵的", level: "CET-4" },
      { word: "perpendicular", meaning: "垂直的；正交的", level: "CET-6" },
    ],
  },
  {
    root: "phon",
    meaning: "声音",
    category: "感官",
    words: [
      { word: "phone", meaning: "电话；音素", level: "CET-4" },
      { word: "telephone", meaning: "电话", level: "CET-4" },
      { word: "microphone", meaning: "麦克风；话筒", level: "CET-4" },
      { word: "symphony", meaning: "交响乐；交响曲", level: "CET-6" },
      { word: "phonetic", meaning: "语音的；语音学的", level: "CET-6" },
      { word: "earphone", meaning: "耳机", level: "CET-4" },
      { word: "headphone", meaning: "头戴式耳机", level: "CET-4" },
    ],
  },
  {
    root: "pon/pos",
    meaning: "放置",
    category: "动作",
    words: [
      { word: "pose", meaning: "姿势；造成；提出", level: "CET-4" },
      { word: "position", meaning: "位置；职位", level: "CET-4" },
      { word: "positive", meaning: "积极的；肯定的", level: "CET-4" },
      { word: "compose", meaning: "组成；创作", level: "CET-4" },
      { word: "composition", meaning: "作文；组成", level: "CET-4" },
      { word: "composer", meaning: "作曲家；创作者", level: "CET-4" },
      { word: "deposit", meaning: "存款；押金；沉淀", level: "CET-4" },
      { word: "dispose", meaning: "处理；安排", level: "CET-4" },
      { word: "disposal", meaning: "处理；处置", level: "CET-4" },
      { word: "expose", meaning: "暴露；揭露", level: "CET-4" },
      { word: "exposure", meaning: "暴露；接触", level: "CET-4" },
      { word: "impose", meaning: "强加；征税", level: "CET-4" },
      { word: "oppose", meaning: "反对；对抗", level: "CET-4" },
      { word: "opposite", meaning: "相反的；对面的", level: "CET-4" },
      { word: "propose", meaning: "提议；求婚", level: "CET-4" },
      { word: "proposal", meaning: "提议；提案", level: "CET-4" },
      { word: "suppose", meaning: "假设；认为", level: "CET-4" },
      { word: "component", meaning: "组件；成分", level: "CET-4" },
      { word: "postpone", meaning: "推迟；延期", level: "CET-4" },
      { word: "compound", meaning: "混合；复合物", level: "CET-4" },
    ],
  },
  {
    root: "port",
    meaning: "搬运，港口",
    category: "动作",
    words: [
      { word: "port", meaning: "港口", level: "CET-4" },
      { word: "portable", meaning: "便携的；轻便的", level: "CET-4" },
      { word: "porter", meaning: "搬运工；门房", level: "CET-4" },
      { word: "export", meaning: "出口；输出", level: "CET-4" },
      { word: "import", meaning: "进口；输入", level: "CET-4" },
      { word: "important", meaning: "重要的；重大的", level: "CET-4" },
      { word: "importance", meaning: "重要性", level: "CET-4" },
      { word: "report", meaning: "报告；报道", level: "CET-4" },
      { word: "reporter", meaning: "记者；通讯员", level: "CET-4" },
      { word: "support", meaning: "支持；援助", level: "CET-4" },
      { word: "transport", meaning: "运输；交通工具", level: "CET-4" },
      { word: "transportation", meaning: "运输；交通", level: "CET-4" },
      { word: "opportunity", meaning: "机会；时机", level: "CET-4" },
      { word: "passport", meaning: "护照", level: "CET-4" },
      { word: "deport", meaning: "驱逐出境", level: "CET-6" },
    ],
  },
  {
    root: "press",
    meaning: "压",
    category: "动作",
    words: [
      { word: "press", meaning: "压；按；新闻界", level: "CET-4" },
      { word: "pressure", meaning: "压力；压迫", level: "CET-4" },
      { word: "compress", meaning: "压缩；压缩", level: "CET-4" },
      { word: "compression", meaning: "压缩；浓缩", level: "CET-6" },
      { word: "depress", meaning: "使沮丧；压低", level: "CET-4" },
      { word: "depression", meaning: "沮丧；萧条", level: "CET-4" },
      { word: "express", meaning: "表达；特快的", level: "CET-4" },
      { word: "expression", meaning: "表达；表情", level: "CET-4" },
      { word: "impress", meaning: "给...深刻印象", level: "CET-4" },
      { word: "impression", meaning: "印象；感想", level: "CET-4" },
      { word: "impressive", meaning: "给人印象深刻的", level: "CET-4" },
      { word: "oppress", meaning: "压迫；压抑", level: "CET-6" },
      { word: "suppress", meaning: "压制；抑制", level: "CET-6" },
    ],
  },
  {
    root: "prim/prin",
    meaning: "第一，首要",
    category: "性质",
    words: [
      { word: "prime", meaning: "首要的；最佳的", level: "CET-4" },
      { word: "primary", meaning: "主要的；初级的", level: "CET-4" },
      { word: "primarily", meaning: "主要地；首先", level: "CET-4" },
      { word: "primitive", meaning: "原始的；简单的", level: "CET-4" },
      { word: "prince", meaning: "王子；亲王", level: "CET-4" },
      { word: "princess", meaning: "公主；王妃", level: "CET-4" },
      { word: "principal", meaning: "主要的；校长", level: "CET-4" },
      { word: "principle", meaning: "原则；原理", level: "CET-4" },
      { word: "premier", meaning: "总理；首位的", level: "CET-6" },
    ],
  },
  {
    root: "psycho",
    meaning: "心理",
    category: "思维",
    words: [
      { word: "psychology", meaning: "心理学", level: "CET-4" },
      { word: "psychological", meaning: "心理的；心理学的", level: "CET-4" },
      { word: "psychologist", meaning: "心理学家", level: "CET-4" },
      { word: "psychiatry", meaning: "精神病学", level: "CET-6" },
      { word: "psychic", meaning: "心灵的；通灵的", level: "CET-6" },
      { word: "psychoanalysis", meaning: "精神分析", level: "CET-6" },
    ],
  },
  {
    root: "pur",
    meaning: "纯净",
    category: "性质",
    words: [
      { word: "pure", meaning: "纯净的；纯粹的", level: "CET-4" },
      { word: "purely", meaning: "纯粹地；完全地", level: "CET-4" },
      { word: "purify", meaning: "净化；提纯", level: "CET-6" },
      { word: "purity", meaning: "纯净；纯洁", level: "CET-6" },
      { word: "impure", meaning: "不纯的；掺杂的", level: "CET-6" },
      { word: "impurity", meaning: "杂质；不纯", level: "CET-6" },
      { word: "puritan", meaning: "清教徒", level: "CET-6" },
    ],
  },
  {
    root: "ques/quir/quis",
    meaning: "询问",
    category: "交流",
    words: [
      { word: "question", meaning: "问题；询问", level: "CET-4" },
      { word: "questionnaire", meaning: "问卷；调查表", level: "CET-4" },
      { word: "quest", meaning: "探索；追求", level: "CET-6" },
      { word: "request", meaning: "请求；要求", level: "CET-4" },
      { word: "acquire", meaning: "获得；学到", level: "CET-4" },
      { word: "acquisition", meaning: "获得；习得", level: "CET-4" },
      { word: "inquire/enquire", meaning: "询问；调查", level: "CET-4" },
      { word: "inquiry/enquiry", meaning: "询问；调查", level: "CET-4" },
      { word: "require", meaning: "需要；要求", level: "CET-4" },
      { word: "requirement", meaning: "要求；必要条件", level: "CET-4" },
      { word: "exquisite", meaning: "精致的；精美的", level: "CET-6" },
      { word: "prerequisite", meaning: "前提；先决条件", level: "CET-6" },
    ],
  },
  {
    root: "rupt",
    meaning: "破，裂",
    category: "动作",
    words: [
      { word: "rupture", meaning: "破裂；断裂", level: "CET-6" },
      { word: "abrupt", meaning: "突然的；唐突的", level: "CET-4" },
      { word: "bankrupt", meaning: "破产的", level: "CET-4" },
      { word: "bankruptcy", meaning: "破产", level: "CET-6" },
      { word: "corrupt", meaning: "腐败的；贪污的", level: "CET-4" },
      { word: "corruption", meaning: "腐败；贪污", level: "CET-4" },
      { word: "disrupt", meaning: "破坏；中断", level: "CET-6" },
      { word: "disruption", meaning: "破坏；中断", level: "CET-6" },
      { word: "erupt", meaning: "爆发；喷发", level: "CET-6" },
      { word: "eruption", meaning: "爆发；喷发", level: "CET-6" },
      { word: "interrupt", meaning: "打断；中断", level: "CET-4" },
      { word: "interruption", meaning: "中断；打断", level: "CET-4" },
    ],
  },
  {
    root: "sci",
    meaning: "知道",
    category: "思维",
    words: [
      { word: "science", meaning: "科学", level: "CET-4" },
      { word: "scientist", meaning: "科学家", level: "CET-4" },
      { word: "scientific", meaning: "科学的", level: "CET-4" },
      { word: "conscience", meaning: "良心；良知", level: "CET-4" },
      { word: "conscientious", meaning: "认真负责的", level: "CET-6" },
      { word: "conscious", meaning: "有意识的；自觉的", level: "CET-4" },
      { word: "consciousness", meaning: "意识；觉悟", level: "CET-4" },
      { word: "subconscious", meaning: "潜意识的", level: "CET-6" },
      { word: "omniscient", meaning: "无所不知的", level: "CET-6" },
      { word: "prescient", meaning: "有预知能力的", level: "CET-6" },
    ],
  },
  {
    root: "scrib/script",
    meaning: "写",
    category: "交流",
    words: [
      { word: "scribe", meaning: "抄写员；书记", level: "CET-6" },
      { word: "script", meaning: "脚本；手稿", level: "CET-4" },
      { word: "describe", meaning: "描述；形容", level: "CET-4" },
      { word: "description", meaning: "描述；说明", level: "CET-4" },
      { word: "prescribe", meaning: "开药方；规定", level: "CET-4" },
      { word: "prescription", meaning: "处方；药方", level: "CET-6" },
      { word: "subscribe", meaning: "订阅；捐款", level: "CET-4" },
      { word: "subscriber", meaning: "订阅者；用户", level: "CET-4" },
      { word: "subscription", meaning: "订阅；订购", level: "CET-6" },
      { word: "inscribe", meaning: "题写；铭刻", level: "CET-6" },
      { word: "inscription", meaning: "铭文；题字", level: "CET-6" },
      { word: "manuscript", meaning: "手稿；原稿", level: "CET-6" },
      { word: "postscript", meaning: "附言；后记", level: "CET-6" },
      { word: "transcribe", meaning: "转录；抄写", level: "CET-6" },
      { word: "transcript", meaning: "成绩单；副本", level: "CET-4" },
    ],
  },
];
