// 词根数据 Part 3: sect ~ 后缀 -ment
const wordRootsPart3 = [
  {
    root: "sect",
    meaning: "切，割",
    category: "动作",
    words: [
      { word: "section", meaning: "部分；章节；区域", level: "CET-4" },
      { word: "sector", meaning: "部门；领域；扇形", level: "CET-4" },
      { word: "dissect", meaning: "解剖；仔细分析", level: "CET-6" },
      { word: "intersect", meaning: "相交；贯穿", level: "CET-6" },
      { word: "intersection", meaning: "交叉路口；交集", level: "CET-6" },
      { word: "insect", meaning: "昆虫", level: "CET-4" },
    ],
  },
  {
    root: "sens/sent",
    meaning: "感觉",
    category: "感官",
    words: [
      { word: "sense", meaning: "感觉；意义；理性", level: "CET-4" },
      { word: "sensation", meaning: "感觉；轰动", level: "CET-6" },
      { word: "sensible", meaning: "明智的；合理的", level: "CET-4" },
      { word: "sensitive", meaning: "敏感的；灵敏的", level: "CET-4" },
      { word: "sensitivity", meaning: "敏感性；灵敏度", level: "CET-6" },
      { word: "sentence", meaning: "句子；判决", level: "CET-4" },
      { word: "sentiment", meaning: "感情；情绪", level: "CET-6" },
      { word: "sentimental", meaning: "多愁善感的", level: "CET-6" },
      { word: "consensus", meaning: "共识；一致意见", level: "CET-4" },
      { word: "consent", meaning: "同意；许可", level: "CET-4" },
      { word: "dissent", meaning: "不同意；异议", level: "CET-6" },
      { word: "resent", meaning: "怨恨；憎恶", level: "CET-6" },
      { word: "resentment", meaning: "怨恨；不满", level: "CET-6" },
      { word: "present", meaning: "礼物；现在的；呈现", level: "CET-4" },
      { word: "represent", meaning: "代表；表示", level: "CET-4" },
      { word: "representative", meaning: "代表；典型的", level: "CET-4" },
    ],
  },
  {
    root: "sequ/sec",
    meaning: "跟随",
    category: "动作",
    words: [
      { word: "sequence", meaning: "顺序；连续", level: "CET-4" },
      { word: "consequence", meaning: "结果；后果", level: "CET-4" },
      { word: "consequent", meaning: "随之发生的", level: "CET-6" },
      { word: "consequently", meaning: "因此；所以", level: "CET-4" },
      { word: "subsequent", meaning: "随后的；后来的", level: "CET-4" },
      { word: "subsequently", meaning: "随后；后来", level: "CET-4" },
      { word: "second", meaning: "第二；秒", level: "CET-4" },
      { word: "secondary", meaning: "次要的；中等的", level: "CET-4" },
      { word: "persecute", meaning: "迫害；困扰", level: "CET-6" },
      { word: "prosecute", meaning: "起诉；执行", level: "CET-6" },
      { word: "execute", meaning: "执行；处决", level: "CET-4" },
      { word: "executive", meaning: "执行的；管理者", level: "CET-4" },
    ],
  },
  {
    root: "solv/solu",
    meaning: "解开",
    category: "动作",
    words: [
      { word: "solve", meaning: "解决；解答", level: "CET-4" },
      { word: "solution", meaning: "解决方案；溶液", level: "CET-4" },
      { word: "soluble", meaning: "可溶的；可解决的", level: "CET-6" },
      { word: "dissolve", meaning: "溶解；解散", level: "CET-4" },
      { word: "resolve", meaning: "解决；决心", level: "CET-4" },
      { word: "resolute", meaning: "坚决的；果断的", level: "CET-6" },
      { word: "resolution", meaning: "决议；决心；分辨率", level: "CET-4" },
      { word: "absolve", meaning: "赦免；解除", level: "CET-6" },
      { word: "absolute", meaning: "绝对的；完全的", level: "CET-4" },
      { word: "absolutely", meaning: "绝对地；完全地", level: "CET-4" },
    ],
  },
  {
    root: "spec/spect",
    meaning: "看",
    category: "感官",
    words: [
      { word: "special", meaning: "特殊的；专门的", level: "CET-4" },
      { word: "specialist", meaning: "专家", level: "CET-4" },
      { word: "specialize", meaning: "专门研究；专攻", level: "CET-4" },
      { word: "species", meaning: "物种；种类", level: "CET-4" },
      { word: "specific", meaning: "具体的；特定的", level: "CET-4" },
      { word: "specify", meaning: "指定；详细说明", level: "CET-4" },
      { word: "specimen", meaning: "标本；样本", level: "CET-4" },
      { word: "spectacle", meaning: "景象；眼镜", level: "CET-6" },
      { word: "spectacular", meaning: "壮观的；惊人的", level: "CET-4" },
      { word: "spectator", meaning: "观众；旁观者", level: "CET-6" },
      { word: "spectrum", meaning: "光谱；范围", level: "CET-6" },
      { word: "inspect", meaning: "检查；视察", level: "CET-4" },
      { word: "inspection", meaning: "检查；视察", level: "CET-4" },
      { word: "inspector", meaning: "检查员；监察员", level: "CET-4" },
      { word: "prospect", meaning: "前景；展望", level: "CET-4" },
      { word: "prospective", meaning: "预期的；未来的", level: "CET-6" },
      { word: "respect", meaning: "尊重；方面", level: "CET-4" },
      { word: "respectable", meaning: "可敬的；体面的", level: "CET-4" },
      { word: "respectful", meaning: "恭敬的；有礼貌的", level: "CET-4" },
      { word: "respective", meaning: "各自的；分别的", level: "CET-4" },
      { word: "suspect", meaning: "怀疑；嫌疑犯", level: "CET-4" },
      { word: "suspicion", meaning: "怀疑；嫌疑", level: "CET-4" },
      { word: "suspicious", meaning: "可疑的；怀疑的", level: "CET-4" },
      { word: "expect", meaning: "期望；预期", level: "CET-4" },
      { word: "expectation", meaning: "期望；预期", level: "CET-4" },
      { word: "unexpected", meaning: "意想不到的", level: "CET-4" },
      { word: "retrospect", meaning: "回顾；追溯", level: "CET-6" },
      { word: "perspective", meaning: "透视图；视角；观点", level: "CET-4" },
      { word: "conspicuous", meaning: "显著的；引人注目的", level: "CET-6" },
    ],
  },
  {
    root: "spir",
    meaning: "呼吸",
    category: "生命",
    words: [
      { word: "spirit", meaning: "精神；灵魂；情绪", level: "CET-4" },
      { word: "spiritual", meaning: "精神的；心灵的", level: "CET-4" },
      { word: "inspire", meaning: "激励；启发；赋予灵感", level: "CET-4" },
      { word: "inspiration", meaning: "灵感；启发", level: "CET-4" },
      { word: "aspire", meaning: "渴望；追求", level: "CET-6" },
      { word: "aspiration", meaning: "渴望；志向", level: "CET-6" },
      { word: "conspire", meaning: "共谋；密谋", level: "CET-6" },
      { word: "conspiracy", meaning: "阴谋；密谋", level: "CET-6" },
      { word: "expire", meaning: "到期；过期", level: "CET-6" },
      { word: "perspire", meaning: "出汗；流汗", level: "CET-6" },
      { word: "respire", meaning: "呼吸", level: "CET-6" },
      { word: "respiratory", meaning: "呼吸的", level: "CET-6" },
      { word: "transpire", meaning: "发生；蒸发", level: "CET-6" },
    ],
  },
  {
    root: "struct",
    meaning: "建造",
    category: "动作",
    words: [
      { word: "structure", meaning: "结构；建筑", level: "CET-4" },
      { word: "structural", meaning: "结构的；构造的", level: "CET-4" },
      { word: "construct", meaning: "建造；构造", level: "CET-4" },
      { word: "construction", meaning: "建设；建筑", level: "CET-4" },
      { word: "destroy", meaning: "破坏；毁灭", level: "CET-4" },
      { word: "destruction", meaning: "破坏；毁灭", level: "CET-4" },
      { word: "destructive", meaning: "破坏性的；毁灭性的", level: "CET-6" },
      { word: "instruct", meaning: "指导；指示", level: "CET-4" },
      { word: "instruction", meaning: "指导；指令；说明", level: "CET-4" },
      { word: "instructor", meaning: "指导员；教练", level: "CET-4" },
      { word: "obstruct", meaning: "阻碍；妨碍", level: "CET-6" },
      { word: "obstruction", meaning: "阻碍；障碍物", level: "CET-6" },
      { word: "reconstruct", meaning: "重建；复原", level: "CET-6" },
      { word: "infrastructure", meaning: "基础设施", level: "CET-4" },
    ],
  },
  {
    root: "tain/ten/tin",
    meaning: "握，持",
    category: "动作",
    words: [
      { word: "contain", meaning: "包含；容纳", level: "CET-4" },
      { word: "container", meaning: "容器；集装箱", level: "CET-4" },
      { word: "obtain", meaning: "获得；得到", level: "CET-4" },
      { word: "maintain", meaning: "维持；保养", level: "CET-4" },
      { word: "maintenance", meaning: "维护；保养", level: "CET-4" },
      { word: "retain", meaning: "保留；保持", level: "CET-4" },
      { word: "retention", meaning: "保留；保持", level: "CET-6" },
      { word: "sustain", meaning: "维持；支撑", level: "CET-4" },
      { word: "sustainable", meaning: "可持续的", level: "CET-4" },
      { word: "detain", meaning: "拘留；扣留", level: "CET-6" },
      { word: "entertain", meaning: "娱乐；款待", level: "CET-4" },
      { word: "entertainment", meaning: "娱乐；款待", level: "CET-4" },
      { word: "tenacious", meaning: "坚韧的；执着的", level: "CET-6" },
      { word: "tenure", meaning: "任期；终身职位", level: "CET-6" },
      { word: "continue", meaning: "继续；延续", level: "CET-4" },
      { word: "continuous", meaning: "连续的；持续的", level: "CET-4" },
      { word: "continent", meaning: "大陆；洲", level: "CET-4" },
      { word: "pertinent", meaning: "相关的；切题的", level: "CET-6" },
    ],
  },
  {
    root: "tend/tens/tent",
    meaning: "伸展",
    category: "动作",
    words: [
      { word: "tend", meaning: "倾向；照顾", level: "CET-4" },
      { word: "tendency", meaning: "趋势；倾向", level: "CET-4" },
      { word: "attend", meaning: "参加；出席；照料", level: "CET-4" },
      { word: "attendance", meaning: "出席；到场", level: "CET-4" },
      { word: "attention", meaning: "注意；注意力", level: "CET-4" },
      { word: "attentive", meaning: "注意的；专心的", level: "CET-4" },
      { word: "extend", meaning: "延伸；扩展", level: "CET-4" },
      { word: "extension", meaning: "扩展；延长", level: "CET-4" },
      { word: "extensive", meaning: "广泛的；大量的", level: "CET-4" },
      { word: "extent", meaning: "程度；范围", level: "CET-4" },
      { word: "intend", meaning: "打算；意图", level: "CET-4" },
      { word: "intense", meaning: "强烈的；紧张的", level: "CET-4" },
      { word: "intensity", meaning: "强度；强烈", level: "CET-4" },
      { word: "intensive", meaning: "深入的；密集的", level: "CET-4" },
      { word: "intention", meaning: "意图；目的", level: "CET-4" },
      { word: "pretend", meaning: "假装；伪装", level: "CET-4" },
      { word: "pretension", meaning: "自命不凡；主张", level: "CET-6" },
      { word: "contend", meaning: "竞争；主张", level: "CET-6" },
      { word: "distend", meaning: "膨胀；扩张", level: "CET-6" },
      { word: "tension", meaning: "紧张；张力", level: "CET-4" },
    ],
  },
  {
    root: "terr",
    meaning: "土地，恐怖",
    category: "自然",
    words: [
      { word: "territory", meaning: "领土；范围", level: "CET-4" },
      { word: "territorial", meaning: "领土的；区域的", level: "CET-6" },
      { word: "terrain", meaning: "地形；地带", level: "CET-6" },
      { word: "terrestrial", meaning: "陆地的；地球的", level: "CET-6" },
      { word: "terrible", meaning: "可怕的；极糟的", level: "CET-4" },
      { word: "terrific", meaning: "极好的；可怕的", level: "CET-4" },
      { word: "terrify", meaning: "恐吓；使恐惧", level: "CET-4" },
      { word: "terror", meaning: "恐怖；恐怖活动", level: "CET-4" },
      { word: "terrorism", meaning: "恐怖主义", level: "CET-4" },
      { word: "terrorist", meaning: "恐怖分子", level: "CET-4" },
      { word: "deterrent", meaning: "威慑的；威慑物", level: "CET-6" },
      { word: "mediterranean", meaning: "地中海", level: "CET-4" },
    ],
  },
  {
    root: "test",
    meaning: "证明，测试",
    category: "评价",
    words: [
      { word: "test", meaning: "测试；试验", level: "CET-4" },
      { word: "testify", meaning: "作证；证明", level: "CET-6" },
      { word: "testimony", meaning: "证词；证据", level: "CET-6" },
      { word: "protest", meaning: "抗议；反对", level: "CET-4" },
      { word: "contest", meaning: "竞赛；争论", level: "CET-4" },
      { word: "contestant", meaning: "参赛者；选手", level: "CET-6" },
      { word: "detest", meaning: "憎恶；厌恶", level: "CET-6" },
      { word: "attest", meaning: "证明；证实", level: "CET-6" },
    ],
  },
  {
    root: "tract",
    meaning: "拉，抽",
    category: "动作",
    words: [
      { word: "tractor", meaning: "拖拉机；牵引车", level: "CET-4" },
      { word: "abstract", meaning: "抽象的；摘要", level: "CET-4" },
      { word: "attract", meaning: "吸引；引起", level: "CET-4" },
      { word: "attraction", meaning: "吸引；吸引力", level: "CET-4" },
      { word: "attractive", meaning: "有吸引力的", level: "CET-4" },
      { word: "contract", meaning: "合同；收缩", level: "CET-4" },
      { word: "contraction", meaning: "收缩；缩小", level: "CET-6" },
      { word: "distract", meaning: "分散注意力", level: "CET-4" },
      { word: "distraction", meaning: "分心；分散注意力的事", level: "CET-6" },
      { word: "extract", meaning: "提取；摘录", level: "CET-4" },
      { word: "extraction", meaning: "提取；取出", level: "CET-6" },
      { word: "subtract", meaning: "减去；扣除", level: "CET-4" },
      { word: "subtraction", meaning: "减法", level: "CET-4" },
      { word: "retract", meaning: "缩回；收回", level: "CET-6" },
      { word: "protract", meaning: "延长；拖延", level: "CET-6" },
      { word: "traction", meaning: "牵引力；附着力", level: "CET-6" },
    ],
  },
  {
    root: "uni",
    meaning: "一，统一",
    category: "数量",
    words: [
      { word: "unit", meaning: "单位；单元", level: "CET-4" },
      { word: "unite", meaning: "联合；统一", level: "CET-4" },
      { word: "union", meaning: "联盟；工会", level: "CET-4" },
      { word: "unique", meaning: "独特的；唯一的", level: "CET-4" },
      { word: "unify", meaning: "统一；使一致", level: "CET-6" },
      { word: "uniform", meaning: "制服；统一的", level: "CET-4" },
      { word: "unilateral", meaning: "单边的；一方的", level: "CET-6" },
      { word: "unanimous", meaning: "一致的；全体同意的", level: "CET-6" },
      { word: "universe", meaning: "宇宙；万物", level: "CET-4" },
      { word: "university", meaning: "大学", level: "CET-4" },
      { word: "reunion", meaning: "重聚；团圆", level: "CET-4" },
    ],
  },
  {
    root: "vac/vacu",
    meaning: "空",
    category: "性质",
    words: [
      { word: "vacuum", meaning: "真空；吸尘器", level: "CET-4" },
      { word: "vacant", meaning: "空缺的；空闲的", level: "CET-4" },
      { word: "vacancy", meaning: "空缺；空位", level: "CET-4" },
      { word: "vacation", meaning: "假期；休假", level: "CET-4" },
      { word: "evacuate", meaning: "疏散；撤离", level: "CET-6" },
      { word: "evacuation", meaning: "疏散；撤离", level: "CET-6" },
      { word: "vanish", meaning: "消失；消散", level: "CET-4" },
    ],
  },
  {
    root: "val/vail",
    meaning: "价值，强",
    category: "评价",
    words: [
      { word: "value", meaning: "价值；价值观", level: "CET-4" },
      { word: "valuable", meaning: "有价值的；宝贵的", level: "CET-4" },
      { word: "evaluate", meaning: "评估；评价", level: "CET-4" },
      { word: "evaluation", meaning: "评估；评价", level: "CET-4" },
      { word: "valid", meaning: "有效的；合理的", level: "CET-4" },
      { word: "validity", meaning: "有效性；合法性", level: "CET-6" },
      { word: "invalid", meaning: "无效的；病弱者", level: "CET-4" },
      { word: "equivalent", meaning: "等价的；相当的", level: "CET-4" },
      { word: "avail", meaning: "有用；有益", level: "CET-6" },
      { word: "available", meaning: "可用的；可得到的", level: "CET-4" },
      { word: "prevail", meaning: "流行；占优势", level: "CET-4" },
      { word: "prevalent", meaning: "流行的；普遍的", level: "CET-6" },
      { word: "ambivalent", meaning: "矛盾的；犹豫不决的", level: "CET-6" },
    ],
  },
  {
    root: "ven/vent",
    meaning: "来",
    category: "动作",
    words: [
      { word: "venture", meaning: "冒险；投机", level: "CET-4" },
      { word: "adventure", meaning: "冒险；奇遇", level: "CET-4" },
      { word: "event", meaning: "事件；活动", level: "CET-4" },
      { word: "eventually", meaning: "最终；最后", level: "CET-4" },
      { word: "invent", meaning: "发明；创造", level: "CET-4" },
      { word: "invention", meaning: "发明；创造", level: "CET-4" },
      { word: "inventor", meaning: "发明家", level: "CET-4" },
      { word: "prevent", meaning: "防止；阻止", level: "CET-4" },
      { word: "prevention", meaning: "预防；防止", level: "CET-4" },
      { word: "convention", meaning: "大会；惯例", level: "CET-4" },
      { word: "conventional", meaning: "传统的；惯例的", level: "CET-4" },
      { word: "intervene", meaning: "干涉；干预", level: "CET-6" },
      { word: "intervention", meaning: "干涉；干预", level: "CET-6" },
      { word: "revenue", meaning: "收入；税收", level: "CET-4" },
      { word: "avenue", meaning: "大道；途径", level: "CET-4" },
      { word: "circumvent", meaning: "绕行；规避", level: "CET-6" },
    ],
  },
  {
    root: "vid/vis",
    meaning: "看",
    category: "感官",
    words: [
      { word: "video", meaning: "视频；录像", level: "CET-4" },
      { word: "visible", meaning: "可见的；明显的", level: "CET-4" },
      { word: "vision", meaning: "视力；远见；景象", level: "CET-4" },
      { word: "visual", meaning: "视觉的；看得见的", level: "CET-4" },
      { word: "visit", meaning: "访问；参观", level: "CET-4" },
      { word: "visitor", meaning: "访客；参观者", level: "CET-4" },
      { word: "advise", meaning: "建议；劝告", level: "CET-4" },
      { word: "advice", meaning: "建议；劝告", level: "CET-4" },
      { word: "adviser/advisor", meaning: "顾问；指导老师", level: "CET-4" },
      { word: "revise", meaning: "修订；复习", level: "CET-4" },
      { word: "revision", meaning: "修订；复习", level: "CET-4" },
      { word: "supervise", meaning: "监督；管理", level: "CET-4" },
      { word: "supervision", meaning: "监督；管理", level: "CET-4" },
      { word: "supervisor", meaning: "主管；监督人", level: "CET-4" },
      { word: "evidence", meaning: "证据；迹象", level: "CET-4" },
      { word: "evident", meaning: "明显的；明白的", level: "CET-4" },
      { word: "provide", meaning: "提供；供给", level: "CET-4" },
      { word: "provision", meaning: "提供；规定；供应", level: "CET-4" },
      { word: "envisage", meaning: "设想；展望", level: "CET-6" },
      { word: "invisible", meaning: "看不见的；隐形的", level: "CET-4" },
      { word: "television", meaning: "电视", level: "CET-4" },
      { word: "visualize", meaning: "设想；想象", level: "CET-6" },
    ],
  },
  {
    root: "vit/viv",
    meaning: "生命",
    category: "生命",
    words: [
      { word: "vital", meaning: "至关重要的；生命的", level: "CET-4" },
      { word: "vitality", meaning: "活力；生命力", level: "CET-6" },
      { word: "vitamin", meaning: "维生素", level: "CET-4" },
      { word: "vivid", meaning: "生动的；鲜明的", level: "CET-4" },
      { word: "survive", meaning: "幸存；生存", level: "CET-4" },
      { word: "survival", meaning: "幸存；生存", level: "CET-4" },
      { word: "survivor", meaning: "幸存者", level: "CET-4" },
      { word: "revive", meaning: "复苏；复兴", level: "CET-6" },
      { word: "revival", meaning: "复兴；复苏", level: "CET-6" },
      { word: "vivacious", meaning: "活泼的；有生气的", level: "CET-6" },
    ],
  },
  {
    root: "voc/voke",
    meaning: "叫，声音",
    category: "交流",
    words: [
      { word: "vocal", meaning: "声音的；直言不讳的", level: "CET-6" },
      { word: "vocation", meaning: "职业；天职", level: "CET-4" },
      { word: "vocational", meaning: "职业的；业务的", level: "CET-4" },
      { word: "vocabulary", meaning: "词汇；词汇量", level: "CET-4" },
      { word: "advocate", meaning: "提倡；拥护；律师", level: "CET-4" },
      { word: "convoke", meaning: "召集；召开", level: "CET-6" },
      { word: "evoke", meaning: "唤起；引起", level: "CET-6" },
      { word: "invoke", meaning: "援引；调用", level: "CET-6" },
      { word: "provoke", meaning: "激怒；挑起", level: "CET-6" },
      { word: "provocative", meaning: "挑衅的；煽动的", level: "CET-6" },
      { word: "revoke", meaning: "撤销；废除", level: "CET-6" },
    ],
  },
  {
    root: "volv/volu",
    meaning: "滚，转",
    category: "动作",
    words: [
      { word: "volve", meaning: "卷；转", level: "CET-6" },
      { word: "involve", meaning: "涉及；包含", level: "CET-4" },
      { word: "involvement", meaning: "参与；牵连", level: "CET-4" },
      { word: "evolve", meaning: "进化；发展", level: "CET-4" },
      { word: "evolution", meaning: "进化；演变", level: "CET-4" },
      { word: "revolve", meaning: "旋转；围绕", level: "CET-6" },
      { word: "revolver", meaning: "左轮手枪", level: "CET-6" },
      { word: "revolution", meaning: "革命；重大变革", level: "CET-4" },
      { word: "revolutionary", meaning: "革命的；革命者", level: "CET-4" },
      { word: "volume", meaning: "卷；音量；体积", level: "CET-4" },
    ],
  },
  {
    root: "前缀:dis-",
    meaning: "不，否定；分开",
    category: "前缀",
    words: [
      { word: "disagree", meaning: "不同意；不一致", level: "CET-4" },
      { word: "disappear", meaning: "消失；不见", level: "CET-4" },
      { word: "disappoint", meaning: "使失望", level: "CET-4" },
      { word: "disapprove", meaning: "不赞成；反对", level: "CET-4" },
      { word: "disclose", meaning: "揭露；公开", level: "CET-6" },
      { word: "disconnect", meaning: "断开；分离", level: "CET-4" },
      { word: "discount", meaning: "折扣", level: "CET-4" },
      { word: "discourage", meaning: "使气馁；阻止", level: "CET-4" },
      { word: "discover", meaning: "发现", level: "CET-4" },
      { word: "discriminate", meaning: "歧视；区别", level: "CET-4" },
      { word: "disease", meaning: "疾病", level: "CET-4" },
      { word: "disguise", meaning: "伪装；掩饰", level: "CET-6" },
      { word: "disgust", meaning: "厌恶；恶心", level: "CET-4" },
      { word: "dismiss", meaning: "解雇；解散", level: "CET-4" },
      { word: "disorder", meaning: "混乱；失调", level: "CET-4" },
      { word: "dispute", meaning: "争论；争议", level: "CET-4" },
      { word: "dissolve", meaning: "溶解；解散", level: "CET-4" },
      { word: "distract", meaning: "分心；打扰", level: "CET-4" },
      { word: "distress", meaning: "痛苦；困境", level: "CET-4" },
      { word: "distribute", meaning: "分配；分发", level: "CET-4" },
    ],
  },
  {
    root: "前缀:re-",
    meaning: "再次；回",
    category: "前缀",
    words: [
      { word: "react", meaning: "反应；回应", level: "CET-4" },
      { word: "reappear", meaning: "再次出现", level: "CET-6" },
      { word: "rebel", meaning: "反叛；反抗", level: "CET-4" },
      { word: "rebuild", meaning: "重建；改造", level: "CET-4" },
      { word: "recall", meaning: "回忆；召回", level: "CET-4" },
      { word: "receive", meaning: "接收；收到", level: "CET-4" },
      { word: "recent", meaning: "最近的；近来的", level: "CET-4" },
      { word: "recession", meaning: "衰退；萧条", level: "CET-4" },
      { word: "recognize", meaning: "认出；承认", level: "CET-4" },
      { word: "recommend", meaning: "推荐；建议", level: "CET-4" },
      { word: "recover", meaning: "恢复；复原", level: "CET-4" },
      { word: "reduce", meaning: "减少；降低", level: "CET-4" },
      { word: "refer", meaning: "参考；提及", level: "CET-4" },
      { word: "reflect", meaning: "反射；反映", level: "CET-4" },
      { word: "reform", meaning: "改革；改造", level: "CET-4" },
      { word: "refresh", meaning: "使恢复；使清新", level: "CET-4" },
      { word: "refund", meaning: "退款；退还", level: "CET-4" },
      { word: "refuse", meaning: "拒绝", level: "CET-4" },
      { word: "regard", meaning: "看待；尊重", level: "CET-4" },
      { word: "reinforce", meaning: "加强；增援", level: "CET-4" },
    ],
  },
  {
    root: "前缀:pre-",
    meaning: "前，预先",
    category: "前缀",
    words: [
      { word: "prearrange", meaning: "预先安排", level: "CET-6" },
      { word: "precede", meaning: "先于；领先", level: "CET-4" },
      { word: "precedent", meaning: "先例；前例", level: "CET-6" },
      { word: "precise", meaning: "精确的；准确的", level: "CET-4" },
      { word: "predict", meaning: "预测；预言", level: "CET-4" },
      { word: "preface", meaning: "序言；前言", level: "CET-6" },
      { word: "prefer", meaning: "更喜欢；偏好", level: "CET-4" },
      { word: "preliminary", meaning: "初步的；预备的", level: "CET-4" },
      { word: "premier", meaning: "总理；首要的", level: "CET-6" },
      { word: "preparation", meaning: "准备；预备", level: "CET-4" },
      { word: "prescribe", meaning: "开药；规定", level: "CET-4" },
      { word: "preserve", meaning: "保存；保护", level: "CET-4" },
      { word: "president", meaning: "总统；校长", level: "CET-4" },
      { word: "prevent", meaning: "防止；阻止", level: "CET-4" },
      { word: "previous", meaning: "以前的；先前的", level: "CET-4" },
    ],
  },
  {
    root: "前缀:inter-",
    meaning: "在中间；相互",
    category: "前缀",
    words: [
      { word: "interact", meaning: "互动；相互作用", level: "CET-4" },
      { word: "intercept", meaning: "拦截；截获", level: "CET-6" },
      { word: "interchange", meaning: "交换；互换", level: "CET-6" },
      { word: "interconnect", meaning: "互相连接", level: "CET-6" },
      { word: "interfere", meaning: "干涉；干预", level: "CET-4" },
      { word: "interference", meaning: "干涉；干预", level: "CET-4" },
      { word: "intermediate", meaning: "中间的；中级的", level: "CET-4" },
      { word: "internal", meaning: "内部的；国内的", level: "CET-4" },
      { word: "international", meaning: "国际的", level: "CET-4" },
      { word: "internet", meaning: "互联网", level: "CET-4" },
      { word: "interpret", meaning: "口译；解释", level: "CET-4" },
      { word: "interrupt", meaning: "打断；中断", level: "CET-4" },
      { word: "intersection", meaning: "交叉点；十字路口", level: "CET-6" },
      { word: "interval", meaning: "间隔；间歇", level: "CET-4" },
      { word: "interview", meaning: "面试；采访", level: "CET-4" },
    ],
  },
  {
    root: "后缀:-tion/-sion",
    meaning: "名词后缀，表示行为、状态",
    category: "后缀",
    words: [
      { word: "action", meaning: "行动；行为", level: "CET-4" },
      { word: "education", meaning: "教育", level: "CET-4" },
      { word: "information", meaning: "信息；情报", level: "CET-4" },
      { word: "production", meaning: "生产；制造", level: "CET-4" },
      { word: "attention", meaning: "注意；注意力", level: "CET-4" },
      { word: "condition", meaning: "条件；状态", level: "CET-4" },
      { word: "decision", meaning: "决定；决议", level: "CET-4" },
      { word: "division", meaning: "分开；部门", level: "CET-4" },
      { word: "expression", meaning: "表达；表情", level: "CET-4" },
      { word: "impression", meaning: "印象；感想", level: "CET-4" },
      { word: "discussion", meaning: "讨论；议论", level: "CET-4" },
      { word: "conclusion", meaning: "结论；结局", level: "CET-4" },
    ],
  },
  {
    root: "后缀:-ly",
    meaning: "副词后缀，表示方式",
    category: "后缀",
    words: [
      { word: "carefully", meaning: "小心地；仔细地", level: "CET-4" },
      { word: "completely", meaning: "完全地；彻底地", level: "CET-4" },
      { word: "definitely", meaning: "明确地；一定", level: "CET-4" },
      { word: "especially", meaning: "特别；尤其", level: "CET-4" },
      { word: "eventually", meaning: "最终；终于", level: "CET-4" },
      { word: "fortunately", meaning: "幸运地", level: "CET-4" },
      { word: "gradually", meaning: "逐渐地", level: "CET-4" },
      { word: "immediately", meaning: "立即；马上", level: "CET-4" },
      { word: "naturally", meaning: "自然地；当然", level: "CET-4" },
      { word: "necessarily", meaning: "必要地；必然地", level: "CET-4" },
      { word: "obviously", meaning: "明显地", level: "CET-4" },
      { word: "particularly", meaning: "特别地；尤其", level: "CET-4" },
      { word: "probably", meaning: "很可能；大概", level: "CET-4" },
      { word: "recently", meaning: "最近", level: "CET-4" },
      { word: "relatively", meaning: "相对地", level: "CET-4" },
    ],
  },
  {
    root: "后缀:-ful",
    meaning: "形容词后缀，表示充满",
    category: "后缀",
    words: [
      { word: "beautiful", meaning: "美丽的；漂亮的", level: "CET-4" },
      { word: "careful", meaning: "小心的；谨慎的", level: "CET-4" },
      { word: "cheerful", meaning: "愉快的；快乐的", level: "CET-4" },
      { word: "fearful", meaning: "害怕的；恐惧的", level: "CET-4" },
      { word: "grateful", meaning: "感激的；感谢的", level: "CET-4" },
      { word: "hopeful", meaning: "有希望的；乐观的", level: "CET-4" },
      { word: "powerful", meaning: "强大的；有力的", level: "CET-4" },
      { word: "successful", meaning: "成功的", level: "CET-4" },
      { word: "useful", meaning: "有用的；有益的", level: "CET-4" },
      { word: "wonderful", meaning: "极好的；精彩的", level: "CET-4" },
    ],
  },
  {
    root: "后缀:-less",
    meaning: "形容词后缀，表示没有",
    category: "后缀",
    words: [
      { word: "careless", meaning: "粗心的；不小心的", level: "CET-4" },
      { word: "endless", meaning: "无尽的；无穷的", level: "CET-4" },
      { word: "helpless", meaning: "无助的；无力的", level: "CET-4" },
      { word: "homeless", meaning: "无家可归的", level: "CET-4" },
      { word: "hopeless", meaning: "无望的；绝望的", level: "CET-4" },
      { word: "meaningless", meaning: "无意义的", level: "CET-4" },
      { word: "nevertheless", meaning: "然而；不过", level: "CET-4" },
      { word: "regardless", meaning: "不管；不顾", level: "CET-4" },
      { word: "restless", meaning: "不安的；焦躁的", level: "CET-4" },
      { word: "worthless", meaning: "无价值的；没用的", level: "CET-4" },
    ],
  },
  {
    root: "后缀:-ment",
    meaning: "名词后缀，表示行为结果",
    category: "后缀",
    words: [
      { word: "achievement", meaning: "成就；成绩", level: "CET-4" },
      { word: "agreement", meaning: "协议；一致", level: "CET-4" },
      { word: "assignment", meaning: "任务；作业", level: "CET-4" },
      { word: "commitment", meaning: "承诺；投入", level: "CET-4" },
      { word: "development", meaning: "发展；开发", level: "CET-4" },
      { word: "environment", meaning: "环境", level: "CET-4" },
      { word: "equipment", meaning: "设备；装备", level: "CET-4" },
      { word: "establishment", meaning: "建立；确立", level: "CET-6" },
      { word: "government", meaning: "政府；治理", level: "CET-4" },
      { word: "improvement", meaning: "改善；改进", level: "CET-4" },
      { word: "investment", meaning: "投资；投入", level: "CET-4" },
      { word: "management", meaning: "管理；经营", level: "CET-4" },
      { word: "movement", meaning: "移动；运动", level: "CET-4" },
      { word: "payment", meaning: "付款；支付", level: "CET-4" },
      { word: "statement", meaning: "声明；陈述", level: "CET-4" },
      { word: "treatment", meaning: "治疗；待遇", level: "CET-4" },
    ],
  },
];
