// 词根数据 Part 1: act/ag ~ grad/gress
const wordRootsPart1 = [
  {
    root: "act/ag",
    meaning: "行动，做",
    category: "动作",
    words: [
      { word: "act", meaning: "行动；表演", level: "CET-4" },
      { word: "action", meaning: "行动；作用", level: "CET-4" },
      { word: "active", meaning: "积极的；活跃的", level: "CET-4" },
      { word: "activity", meaning: "活动；活跃", level: "CET-4" },
      { word: "actor", meaning: "演员", level: "CET-4" },
      { word: "actress", meaning: "女演员", level: "CET-4" },
      { word: "react", meaning: "反应；回应", level: "CET-4" },
      { word: "reaction", meaning: "反应；反作用", level: "CET-4" },
      { word: "interact", meaning: "相互作用；互动", level: "CET-4" },
      { word: "interaction", meaning: "相互作用；交流", level: "CET-4" },
      { word: "transaction", meaning: "交易；办理", level: "CET-4" },
      { word: "actual", meaning: "实际的；真实的", level: "CET-4" },
      { word: "exact", meaning: "精确的；准确的", level: "CET-4" },
      { word: "enact", meaning: "颁布；制定", level: "CET-6" },
      { word: "agenda", meaning: "议程；日程", level: "CET-4" },
      { word: "agent", meaning: "代理人；代理商", level: "CET-4" },
      { word: "agency", meaning: "代理；机构", level: "CET-4" },
      { word: "agile", meaning: "敏捷的；灵活的", level: "CET-6" },
    ],
  },
  {
    root: "audi",
    meaning: "听",
    category: "感官",
    words: [
      { word: "audio", meaning: "音频的；声音的", level: "CET-4" },
      { word: "audit", meaning: "审计；旁听", level: "CET-4" },
      { word: "auditor", meaning: "审计员；旁听生", level: "CET-6" },
      { word: "audience", meaning: "观众；听众", level: "CET-4" },
      { word: "auditorium", meaning: "礼堂；音乐厅", level: "CET-6" },
      { word: "audible", meaning: "听得见的", level: "CET-6" },
      { word: "inaudible", meaning: "听不见的", level: "CET-6" },
    ],
  },
  {
    root: "auto",
    meaning: "自己，自动",
    category: "性质",
    words: [
      { word: "auto", meaning: "汽车", level: "CET-4" },
      { word: "automatic", meaning: "自动的；无意识的", level: "CET-4" },
      { word: "automatically", meaning: "自动地", level: "CET-4" },
      { word: "automation", meaning: "自动化", level: "CET-4" },
      { word: "automobile", meaning: "汽车", level: "CET-4" },
      { word: "autonomous", meaning: "自治的；自主的", level: "CET-6" },
      { word: "autonomy", meaning: "自治权；自主", level: "CET-6" },
      { word: "autobiography", meaning: "自传", level: "CET-6" },
    ],
  },
  {
    root: "bell",
    meaning: "战争",
    category: "社会",
    words: [
      { word: "rebel", meaning: "反叛；叛逆者", level: "CET-4" },
      { word: "rebellion", meaning: "反叛；起义", level: "CET-6" },
      { word: "belligerent", meaning: "好战的；交战中的", level: "CET-6" },
      { word: "bellicose", meaning: "好斗的；好战的", level: "CET-6" },
      { word: "antebellum", meaning: "战前的", level: "CET-6" },
    ],
  },
  {
    root: "bene",
    meaning: "好",
    category: "评价",
    words: [
      { word: "benefit", meaning: "利益；好处；受益", level: "CET-4" },
      { word: "beneficial", meaning: "有益的；有利的", level: "CET-4" },
      { word: "beneficiary", meaning: "受益人；受惠者", level: "CET-6" },
      { word: "benevolent", meaning: "仁慈的；慈善的", level: "CET-6" },
      { word: "benediction", meaning: "祝福；恩赐", level: "CET-6" },
      { word: "benevolence", meaning: "仁慈；善行", level: "CET-6" },
    ],
  },
  {
    root: "bio",
    meaning: "生命，生物",
    category: "科学",
    words: [
      { word: "biology", meaning: "生物学", level: "CET-4" },
      { word: "biological", meaning: "生物学的", level: "CET-4" },
      { word: "biologist", meaning: "生物学家", level: "CET-4" },
      { word: "biography", meaning: "传记", level: "CET-4" },
      { word: "antibiotic", meaning: "抗生素；抗菌的", level: "CET-6" },
      { word: "biochemistry", meaning: "生物化学", level: "CET-6" },
      { word: "biodegradable", meaning: "可生物降解的", level: "CET-6" },
      { word: "symbiosis", meaning: "共生关系", level: "CET-6" },
    ],
  },
  {
    root: "cap/cip/cept",
    meaning: "拿，取",
    category: "动作",
    words: [
      { word: "capable", meaning: "有能力的；能干的", level: "CET-4" },
      { word: "capacity", meaning: "能力；容量", level: "CET-4" },
      { word: "capture", meaning: "捕获；夺取", level: "CET-4" },
      { word: "captive", meaning: "俘虏；被俘的", level: "CET-6" },
      { word: "accept", meaning: "接受；承认", level: "CET-4" },
      { word: "acceptance", meaning: "接受；认可", level: "CET-4" },
      { word: "concept", meaning: "概念；观念", level: "CET-4" },
      { word: "conception", meaning: "概念；构想", level: "CET-6" },
      { word: "except", meaning: "除了；排除", level: "CET-4" },
      { word: "exception", meaning: "例外；异议", level: "CET-4" },
      { word: "receive", meaning: "接收；收到", level: "CET-4" },
      { word: "reception", meaning: "接待；接收", level: "CET-4" },
      { word: "perceive", meaning: "察觉；感知", level: "CET-4" },
      { word: "perception", meaning: "感知；认识", level: "CET-4" },
      { word: "anticipate", meaning: "预期；期望", level: "CET-4" },
      { word: "participate", meaning: "参与；参加", level: "CET-4" },
      { word: "recipe", meaning: "食谱；秘诀", level: "CET-4" },
    ],
  },
  {
    root: "capit",
    meaning: "头",
    category: "身体",
    words: [
      { word: "capital", meaning: "首都；资本；重要的", level: "CET-4" },
      { word: "captain", meaning: "队长；船长", level: "CET-4" },
      { word: "capitalism", meaning: "资本主义", level: "CET-4" },
      { word: "capitalist", meaning: "资本家", level: "CET-6" },
      { word: "decapitate", meaning: "斩首", level: "CET-6" },
    ],
  },
  {
    root: "ced/ceed/cess",
    meaning: "走，行",
    category: "动作",
    words: [
      { word: "proceed", meaning: "继续进行", level: "CET-4" },
      { word: "procedure", meaning: "程序；步骤", level: "CET-4" },
      { word: "process", meaning: "过程；处理", level: "CET-4" },
      { word: "procession", meaning: "队伍；行列", level: "CET-4" },
      { word: "succeed", meaning: "成功；继承", level: "CET-4" },
      { word: "success", meaning: "成功；成就", level: "CET-4" },
      { word: "successful", meaning: "成功的", level: "CET-4" },
      { word: "succession", meaning: "连续；继承", level: "CET-4" },
      { word: "successive", meaning: "连续的；接连的", level: "CET-4" },
      { word: "exceed", meaning: "超过；超越", level: "CET-4" },
      { word: "excess", meaning: "超过；过剩", level: "CET-4" },
      { word: "excessive", meaning: "过度的；过分的", level: "CET-4" },
      { word: "precede", meaning: "先于；领先", level: "CET-4" },
      { word: "preceding", meaning: "在前的；在先的", level: "CET-4" },
      { word: "recede", meaning: "后退；退却", level: "CET-6" },
      { word: "concede", meaning: "承认；退让", level: "CET-6" },
      { word: "access", meaning: "接近；入口", level: "CET-4" },
      { word: "accessible", meaning: "可接近的", level: "CET-4" },
    ],
  },
  {
    root: "cent",
    meaning: "百",
    category: "数量",
    words: [
      { word: "cent", meaning: "分；百", level: "CET-4" },
      { word: "century", meaning: "世纪；百年", level: "CET-4" },
      { word: "percent", meaning: "百分比", level: "CET-4" },
      { word: "percentage", meaning: "百分比；比例", level: "CET-4" },
      { word: "centigrade", meaning: "摄氏的", level: "CET-4" },
      { word: "centimeter", meaning: "厘米", level: "CET-4" },
      { word: "centenarian", meaning: "百岁老人", level: "CET-6" },
    ],
  },
  {
    root: "cid/cis",
    meaning: "杀，切",
    category: "动作",
    words: [
      { word: "decide", meaning: "决定；裁决", level: "CET-4" },
      { word: "decision", meaning: "决定；决心", level: "CET-4" },
      { word: "decisive", meaning: "决定性的；果断的", level: "CET-4" },
      { word: "precise", meaning: "精确的；准确的", level: "CET-4" },
      { word: "precision", meaning: "精确性；精密度", level: "CET-4" },
      { word: "suicide", meaning: "自杀；自毁", level: "CET-4" },
      { word: "incision", meaning: "切口；切开", level: "CET-6" },
      { word: "concise", meaning: "简洁的；简明的", level: "CET-6" },
    ],
  },
  {
    root: "claim/clam",
    meaning: "叫喊",
    category: "交流",
    words: [
      { word: "claim", meaning: "声称；要求；索赔", level: "CET-4" },
      { word: "exclaim", meaning: "呼喊；惊叫", level: "CET-4" },
      { word: "exclamation", meaning: "感叹；惊叫", level: "CET-6" },
      { word: "proclaim", meaning: "宣告；声明", level: "CET-6" },
      { word: "acclaim", meaning: "欢呼；称赞", level: "CET-6" },
      { word: "disclaim", meaning: "否认；放弃", level: "CET-6" },
      { word: "clamor", meaning: "喧闹；叫嚣", level: "CET-6" },
    ],
  },
  {
    root: "clud/clus",
    meaning: "关闭",
    category: "动作",
    words: [
      { word: "include", meaning: "包括；包含", level: "CET-4" },
      { word: "inclusion", meaning: "包含；包括", level: "CET-4" },
      { word: "inclusive", meaning: "包含的；包括的", level: "CET-4" },
      { word: "exclude", meaning: "排除；排斥", level: "CET-4" },
      { word: "exclusion", meaning: "排除；排斥", level: "CET-6" },
      { word: "exclusive", meaning: "独占的；排外的", level: "CET-4" },
      { word: "conclude", meaning: "结论；结束", level: "CET-4" },
      { word: "conclusion", meaning: "结论；结局", level: "CET-4" },
      { word: "conclusive", meaning: "决定性的", level: "CET-6" },
      { word: "preclude", meaning: "阻止；排除", level: "CET-6" },
      { word: "seclude", meaning: "隔离；隐退", level: "CET-6" },
      { word: "seclusion", meaning: "隔离；隐居", level: "CET-6" },
    ],
  },
  {
    root: "cogn",
    meaning: "知道",
    category: "思维",
    words: [
      { word: "cognition", meaning: "认知；认识", level: "CET-6" },
      { word: "cognitive", meaning: "认知的；认识的", level: "CET-6" },
      { word: "recognize", meaning: "认出；承认", level: "CET-4" },
      { word: "recognition", meaning: "认出；承认", level: "CET-4" },
      { word: "incognito", meaning: "隐姓埋名的", level: "CET-6" },
      { word: "cognizant", meaning: "认知的；知晓的", level: "CET-6" },
    ],
  },
  {
    root: "corp",
    meaning: "身体",
    category: "身体",
    words: [
      { word: "corps", meaning: "军团；队伍", level: "CET-6" },
      { word: "corpse", meaning: "尸体", level: "CET-6" },
      { word: "corporate", meaning: "公司的；法人的", level: "CET-4" },
      { word: "corporation", meaning: "公司；企业", level: "CET-4" },
      { word: "incorporate", meaning: "合并；包含", level: "CET-6" },
      { word: "corporeal", meaning: "肉体的；物质的", level: "CET-6" },
    ],
  },
  {
    root: "cred",
    meaning: "相信",
    category: "评价",
    words: [
      { word: "credit", meaning: "信用；学分；信誉", level: "CET-4" },
      { word: "credible", meaning: "可信的；可靠的", level: "CET-4" },
      { word: "incredible", meaning: "难以置信的", level: "CET-4" },
      { word: "credential", meaning: "证书；凭证", level: "CET-6" },
      { word: "creditor", meaning: "债权人", level: "CET-6" },
      { word: "creed", meaning: "信条；教义", level: "CET-6" },
      { word: "accredit", meaning: "授权；认可", level: "CET-6" },
      { word: "discredit", meaning: "怀疑；使丧失信誉", level: "CET-6" },
    ],
  },
  {
    root: "cur/curs/cour",
    meaning: "跑",
    category: "动作",
    words: [
      { word: "current", meaning: "当前的；流动的", level: "CET-4" },
      { word: "currency", meaning: "货币；流通", level: "CET-4" },
      { word: "occur", meaning: "发生；出现", level: "CET-4" },
      { word: "occurrence", meaning: "发生；事件", level: "CET-4" },
      { word: "recur", meaning: "复发；重现", level: "CET-6" },
      { word: "recurring", meaning: "反复发生的", level: "CET-6" },
      { word: "course", meaning: "课程；过程；路线", level: "CET-4" },
      { word: "intercourse", meaning: "交流；交际", level: "CET-6" },
      { word: "cursor", meaning: "光标；游标", level: "CET-6" },
      { word: "courier", meaning: "快递员；信使", level: "CET-6" },
      { word: "excursion", meaning: "远足；短途旅行", level: "CET-4" },
      { word: "curriculum", meaning: "课程", level: "CET-4" },
    ],
  },
  {
    root: "dict",
    meaning: "说",
    category: "交流",
    words: [
      { word: "dictate", meaning: "口述；命令", level: "CET-4" },
      { word: "dictation", meaning: "听写；口述", level: "CET-4" },
      { word: "dictator", meaning: "独裁者；命令者", level: "CET-6" },
      { word: "dictionary", meaning: "词典；字典", level: "CET-4" },
      { word: "predict", meaning: "预测；预言", level: "CET-4" },
      { word: "prediction", meaning: "预测；预言", level: "CET-4" },
      { word: "contradict", meaning: "反驳；矛盾", level: "CET-4" },
      { word: "contradiction", meaning: "矛盾；反驳", level: "CET-4" },
      { word: "addict", meaning: "上瘾；成瘾者", level: "CET-4" },
      { word: "addiction", meaning: "上瘾；沉溺", level: "CET-6" },
      { word: "dedicate", meaning: "致力于；献身", level: "CET-4" },
      { word: "indicate", meaning: "表明；指示", level: "CET-4" },
      { word: "indication", meaning: "指示；迹象", level: "CET-4" },
      { word: "verdict", meaning: "裁决；定论", level: "CET-6" },
      { word: "benediction", meaning: "祝福；恩赐", level: "CET-6" },
    ],
  },
  {
    root: "duc/duct",
    meaning: "引导",
    category: "动作",
    words: [
      { word: "educate", meaning: "教育；培养", level: "CET-4" },
      { word: "education", meaning: "教育；训练", level: "CET-4" },
      { word: "introduce", meaning: "介绍；引进", level: "CET-4" },
      { word: "introduction", meaning: "介绍；引入", level: "CET-4" },
      { word: "produce", meaning: "生产；制造", level: "CET-4" },
      { word: "production", meaning: "生产；产品", level: "CET-4" },
      { word: "reduce", meaning: "减少；降低", level: "CET-4" },
      { word: "reduction", meaning: "减少；缩小", level: "CET-4" },
      { word: "conduct", meaning: "行为；指挥；引导", level: "CET-4" },
      { word: "conductor", meaning: "指挥；售票员", level: "CET-4" },
      { word: "deduce", meaning: "推论；演绎", level: "CET-6" },
      { word: "induce", meaning: "诱导；引起", level: "CET-6" },
      { word: "induction", meaning: "就职；归纳", level: "CET-6" },
      { word: "aqueduct", meaning: "导水管；沟渠", level: "CET-6" },
      { word: "viaduct", meaning: "高架桥", level: "CET-6" },
    ],
  },
  {
    root: "equi",
    meaning: "相等",
    category: "性质",
    words: [
      { word: "equal", meaning: "相等的；平等的", level: "CET-4" },
      { word: "equality", meaning: "平等；相等", level: "CET-4" },
      { word: "equation", meaning: "等式；方程式", level: "CET-4" },
      { word: "equator", meaning: "赤道", level: "CET-4" },
      { word: "equivalent", meaning: "等价的；相等的", level: "CET-4" },
      { word: "adequate", meaning: "足够的；适当的", level: "CET-4" },
      { word: "equity", meaning: "公平；公正", level: "CET-6" },
      { word: "equitable", meaning: "公平的；公正的", level: "CET-6" },
    ],
  },
  {
    root: "fact/fac/fect",
    meaning: "做，制造",
    category: "动作",
    words: [
      { word: "fact", meaning: "事实；真相", level: "CET-4" },
      { word: "factor", meaning: "因素；要素", level: "CET-4" },
      { word: "factory", meaning: "工厂", level: "CET-4" },
      { word: "faculty", meaning: "才能；全体教员", level: "CET-4" },
      { word: "manufacture", meaning: "制造；生产", level: "CET-4" },
      { word: "manufacturer", meaning: "制造商", level: "CET-4" },
      { word: "affect", meaning: "影响；感动", level: "CET-4" },
      { word: "affection", meaning: "感情；喜爱", level: "CET-4" },
      { word: "effect", meaning: "效果；影响", level: "CET-4" },
      { word: "effective", meaning: "有效的", level: "CET-4" },
      { word: "defect", meaning: "缺陷；欠缺", level: "CET-4" },
      { word: "defective", meaning: "有缺陷的", level: "CET-6" },
      { word: "infect", meaning: "感染；传染", level: "CET-4" },
      { word: "infection", meaning: "感染；传染", level: "CET-4" },
      { word: "perfect", meaning: "完美的；极好的", level: "CET-4" },
      { word: "facilitate", meaning: "使容易；促进", level: "CET-6" },
      { word: "facility", meaning: "设施；设备", level: "CET-4" },
    ],
  },
  {
    root: "fer",
    meaning: "带，拿",
    category: "动作",
    words: [
      { word: "confer", meaning: "商议；授予", level: "CET-4" },
      { word: "conference", meaning: "会议；讨论会", level: "CET-4" },
      { word: "differ", meaning: "不同；差异", level: "CET-4" },
      { word: "difference", meaning: "差异；不同", level: "CET-4" },
      { word: "different", meaning: "不同的", level: "CET-4" },
      { word: "infer", meaning: "推断；推论", level: "CET-4" },
      { word: "inference", meaning: "推断；结论", level: "CET-6" },
      { word: "offer", meaning: "提供；提出", level: "CET-4" },
      { word: "prefer", meaning: "更喜欢", level: "CET-4" },
      { word: "preference", meaning: "偏爱；优先", level: "CET-4" },
      { word: "refer", meaning: "参考；提及", level: "CET-4" },
      { word: "reference", meaning: "参考；参照", level: "CET-4" },
      { word: "transfer", meaning: "转移；调动", level: "CET-4" },
      { word: "fertile", meaning: "肥沃的；富饶的", level: "CET-4" },
      { word: "fertilizer", meaning: "肥料", level: "CET-4" },
      { word: "circumference", meaning: "圆周；周长", level: "CET-6" },
    ],
  },
  {
    root: "fid",
    meaning: "信任",
    category: "评价",
    words: [
      { word: "confident", meaning: "自信的；有信心的", level: "CET-4" },
      { word: "confidence", meaning: "信心；信任", level: "CET-4" },
      { word: "confidential", meaning: "机密的；秘密的", level: "CET-6" },
      { word: "fidelity", meaning: "忠诚；保真度", level: "CET-6" },
      { word: "infidel", meaning: "不信教者", level: "CET-6" },
    ],
  },
  {
    root: "fin",
    meaning: "结束，界限",
    category: "性质",
    words: [
      { word: "finish", meaning: "完成；结束", level: "CET-4" },
      { word: "final", meaning: "最终的；决定性的", level: "CET-4" },
      { word: "finally", meaning: "最后；终于", level: "CET-4" },
      { word: "finance", meaning: "财务；金融", level: "CET-4" },
      { word: "financial", meaning: "金融的；财政的", level: "CET-4" },
      { word: "define", meaning: "定义；界定", level: "CET-4" },
      { word: "definition", meaning: "定义；清晰度", level: "CET-4" },
      { word: "definite", meaning: "明确的；肯定的", level: "CET-4" },
      { word: "definitely", meaning: "明确地；肯定地", level: "CET-4" },
      { word: "infinite", meaning: "无限的；无穷的", level: "CET-4" },
      { word: "confine", meaning: "限制；禁闭", level: "CET-4" },
      { word: "refine", meaning: "精炼；改善", level: "CET-4" },
      { word: "refinery", meaning: "精炼厂", level: "CET-6" },
    ],
  },
  {
    root: "flict",
    meaning: "打击",
    category: "动作",
    words: [
      { word: "conflict", meaning: "冲突；矛盾", level: "CET-4" },
      { word: "afflict", meaning: "折磨；使痛苦", level: "CET-6" },
      { word: "inflict", meaning: "施加；使遭受", level: "CET-6" },
      { word: "affliction", meaning: "痛苦；苦难", level: "CET-6" },
    ],
  },
  {
    root: "form",
    meaning: "形状",
    category: "性质",
    words: [
      { word: "form", meaning: "形式；形状；表格", level: "CET-4" },
      { word: "formal", meaning: "正式的；形式上的", level: "CET-4" },
      { word: "format", meaning: "格式；版式", level: "CET-4" },
      { word: "formation", meaning: "形成；构成", level: "CET-4" },
      { word: "reform", meaning: "改革；革新", level: "CET-4" },
      { word: "transform", meaning: "转变；改造", level: "CET-4" },
      { word: "transformation", meaning: "转变；改革", level: "CET-4" },
      { word: "uniform", meaning: "制服；统一的", level: "CET-4" },
      { word: "inform", meaning: "通知；告知", level: "CET-4" },
      { word: "information", meaning: "信息；情报", level: "CET-4" },
      { word: "conform", meaning: "符合；遵守", level: "CET-6" },
      { word: "perform", meaning: "表现；执行；表演", level: "CET-4" },
      { word: "performance", meaning: "表现；表演；性能", level: "CET-4" },
      { word: "platform", meaning: "平台；站台", level: "CET-4" },
      { word: "formula", meaning: "公式；方案", level: "CET-4" },
    ],
  },
  {
    root: "gen",
    meaning: "产生，种族",
    category: "生命",
    words: [
      { word: "gene", meaning: "基因", level: "CET-4" },
      { word: "general", meaning: "一般的；将军", level: "CET-4" },
      { word: "generally", meaning: "通常；普遍地", level: "CET-4" },
      { word: "generate", meaning: "产生；发生", level: "CET-4" },
      { word: "generation", meaning: "一代；产生", level: "CET-4" },
      { word: "generator", meaning: "发电机；发生器", level: "CET-4" },
      { word: "generous", meaning: "慷慨的；大方的", level: "CET-4" },
      { word: "genetic", meaning: "遗传的；基因的", level: "CET-4" },
      { word: "genius", meaning: "天才；天赋", level: "CET-4" },
      { word: "genuine", meaning: "真正的；真诚的", level: "CET-4" },
      { word: "degenerate", meaning: "退化；堕落", level: "CET-6" },
      { word: "homogeneous", meaning: "同质的；均匀的", level: "CET-6" },
      { word: "heterogeneous", meaning: "异质的；多样的", level: "CET-6" },
      { word: "ingenious", meaning: "巧妙的；聪明的", level: "CET-6" },
      { word: "pregnant", meaning: "怀孕的；充满的", level: "CET-4" },
    ],
  },
  {
    root: "grad/gress",
    meaning: "步，走",
    category: "动作",
    words: [
      { word: "grade", meaning: "等级；年级；评分", level: "CET-4" },
      { word: "gradual", meaning: "逐渐的；渐进的", level: "CET-4" },
      { word: "graduate", meaning: "毕业；毕业生", level: "CET-4" },
      { word: "graduation", meaning: "毕业；毕业典礼", level: "CET-4" },
      { word: "progress", meaning: "进步；进展", level: "CET-4" },
      { word: "progressive", meaning: "进步的；渐进的", level: "CET-4" },
      { word: "aggressive", meaning: "侵略的；好斗的", level: "CET-4" },
      { word: "congress", meaning: "国会；代表大会", level: "CET-4" },
      { word: "degrade", meaning: "降级；退化", level: "CET-6" },
      { word: "upgrade", meaning: "升级；提升", level: "CET-4" },
      { word: "retrogress", meaning: "倒退；退化", level: "CET-6" },
    ],
  },
];
